### ISSUE TITLE
Code répliqué à encapsuler dans une fonction, et à extraire dans aidService

### ISSUE THREAD

**Issue by samuelpath** [betagouv/relance-transformation#51]
Dans `Home.vue`, le code suivant est répliqué 3 fois dans 3 fonctions différentes, avec juste l'URL qui change à chaque fois:

```js
const axios = require("axios");
axios.get(`https://staging.aides-territoires.beta.gouv.fr/api/aids/?backers=505-mtfp&in_france_relance=true&targeted_audiences=commune&targeted_audiences=epci&targeted_audiences=department&targeted_audiences=region`)
  .then(response => {
    this.aides = response.data.results;
  })
}
```

Je propose d'encapsuler ce code dans une fonction nommée `setAidesFromUrlDataResults` qui prendra simplement l'URL en paramètre.

De plus, en m'inspirant du commit suivant de @lazybird: 5d0dd87, je pense qu'il faudrait encapsuler la requête dans aidService. Je vais essayer de l'implémenter rapidement.

**Comment by samuelpath** [comment]
@SarahRubio vu que tu es l'autrice de ce code, que penses-tu de ma proposition?

**Comment by samuelpath** [comment]
@SarahRubio En fait mon commit ne va pas assez loin encore, car du commit suivant de @lazybird: https://github.com/betagouv/relance-transformation/commit/5d0dd87ac277cccc05b33b0c1dcb8607a9a88a4e, je pense qu'il faudrait encapsuler la requête dans `aidService`. Je vais essayer de l'implémenter rapidement.

**Comment by SarahRubio** [comment]
Hello @samuelpath,

Je suis désolée je n'ai pas pris le temps de te répondre aujourd'hui mais
merci pour tes PR, j'ai appris pas mal de choses grâce à elles!  :)

Belle soirée.

**Comment by samuelpath** [comment]
Hello @SarahRubio,

Merci pour ta réponse, c'est sympa de prendre le temps car j'ai conscience que vous êtes sous pression ;).

Thibault m'a indiqué qu'il était trop compliqué d'intégrer mes PR car je ne suis pas dans vos canaux de communication, ce que je comprend tout à fait.
Du coup je suis ravi d'apprendre qu'ils t'aient été utiles pour apprendre des choses :).

Serais-tu partante que si je trouve quelques minutes ici et là la semaine prochaine, je parcoure tes divers commits et te fasse des commentaires? Ces derniers n'auraient bien sûr pas la vocation de proposer des vérités absolues, mais plutôt juste des idées, des suggestions et une perspective externe?

Ce serait une manière pour moi de contribuer un peu sans interférer avec vos PR.

Qu'en penses-tu?

Bon WE à toi.

**Comment by SarahRubio** [comment]
Hello @samuelpath, 

Merci pour ta proposition et tes commentaires. Actuellement les notifications github sont republiées sur le canal de toute l'équipe ce qui ajoute au nombre d'informations déjà présentes sur le dit canal et fait perdre de la lisibilité, je ne peux donc malheureusement pas dire oui à ta proposition. :(

Je suis disponible pour échanger sur le sujet si tu le souhaites via mon adresse sarahrubio.pro@gmail.com :) 

Bonne journée à toi.
